# Generated by Django 2.1.8 on 2020-08-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, unique=True)),
                ('phonenum', models.CharField(max_length=16, unique=True)),
                ('sex', models.CharField(choices=[('男性', '男性'), ('女性', '女性')], max_length=8)),
                ('birth_year', models.IntegerField(verbose_name='出生年')),
                ('birth_month', models.IntegerField(verbose_name='出生月')),
                ('birth_day', models.IntegerField(verbose_name='出生日')),
                ('avator', models.CharField(max_length=256, verbose_name='个人形象')),
                ('location', models.CharField(max_length=32, verbose_name='长居地')),
            ],
        ),
    ]
