# Generated by Django 2.1.8 on 2020-08-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField()),
                ('uid2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动者的UID')),
                ('sid', models.IntegerField(verbose_name='被滑动者的UID')),
                ('flag', models.CharField(choices=[('superlike', '上划'), ('like', '左滑'), ('dislike', '右滑')], max_length=10)),
                ('dtime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
