# Generated by Django 2.1.8 on 2020-08-14 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swiped',
            options={'get_latest_by': 'dtime'},
        ),
    ]
